---
- hosts: 127.0.0.1
  connection: local
  sudo: yes
  vars:
    rbenv_root: /usr/local/rbenv
    ansible_rbenv_root: /usr/local/ansible-rbenv
    # ruby_version: 2.1.2
  tasks:
    - include: tasks/ruby.yml ruby_version=2.1.2